\i ./chunk_test_pgplsql/seed_test_table_int_int_pk.sql
\i ./chunk_test_pgplsql/seed_test_table_int_pk.sql
\i ./chunk_test_pgplsql/seed_test_table_v_pk.sql
\i ./chunk_test_pgplsql/seed_test_table_t_pk.sql
\i ./chunk_test_pgplsql/test_insert_test_table_int_int_pk.sql
\i ./chunk_test_pgplsql/test_insert_test_table_int_pk.sql
\i ./chunk_test_pgplsql/test_insert_test_table_v_pk.sql
\i ./chunk_test_pgplsql/test_insert_test_table_t_pk.sql
\i ./chunk_test_pgplsql/validate_test_table.sql
\i ./chunk_test_pgplsql/assert_uncompleted_run.sql