\i ./plpgsql/chunk_pgplsql_const/chunk_test_data_target_schema.sql
\i ./plpgsql/chunk_pgplsql_const/pk_key1_tag.sql
\i ./plpgsql/chunk_pgplsql_const/pk_key2_tag.sql
\i ./plpgsql/chunk_pgplsql_const/pk_key3_tag.sql
\i ./plpgsql/chunk_pgplsql_const/pk_key4_tag.sql
\i ./plpgsql/chunk_pgplsql_const/driving_table_tag.sql
\i ./plpgsql/chunk_pgplsql_const/table_alias_tag.sql
\i ./plpgsql/chunk_pgplsql_const/chunk_test_data_source_schema.sql
\i ./plpgsql/chunk_pgplsql_const/primary_key_range_tag.sql
\i ./plpgsql/chunk_pgplsql_const/integer_type.sql
\i ./plpgsql/chunk_pgplsql_const/varchar_type.sql
\i ./plpgsql/chunk_pgplsql_const/timestamptz_type.sql

\i ./plpgsql/chunk_pgplsql_lib/log_line.sql
\i ./plpgsql/chunk_pgplsql_lib/validate_statement_text.sql
\i ./plpgsql/chunk_pgplsql_lib/pk1_execute_final.sql
\i ./plpgsql/chunk_pgplsql_lib/pk1_execute_k1_n.sql
\i ./plpgsql/chunk_pgplsql_lib/instr.sql
\i ./plpgsql/chunk_pgplsql_lib/log_chunk_progress.sql
\i ./plpgsql/chunk_pgplsql_lib/pk1_execute_chunks.sql
\i ./plpgsql/chunk_pgplsql_lib/pk2_execute_chunks.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_execute_chunks.sql
\i ./plpgsql/chunk_pgplsql_lib/get_chunk_boundary.sql
\i ./plpgsql/chunk_pgplsql_lib/validate_param_not_null.sql
\i ./plpgsql/chunk_pgplsql_lib/update_run_complete.sql
\i ./plpgsql/chunk_pgplsql_lib/validate_driving_table.sql
\i ./plpgsql/chunk_pgplsql_lib/pk1_get_chunk_statements.sql
\i ./plpgsql/chunk_pgplsql_lib/pk2_get_chunk_statements.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_get_chunk_statements.sql
\i ./plpgsql/chunk_pgplsql_lib/get_chunk_range_query.sql
\i ./plpgsql/chunk_pgplsql_lib/update_chunk_metadata.sql
\i ./plpgsql/chunk_pgplsql_lib/p_replace.sql
\i ./plpgsql/chunk_pgplsql_lib/execute_chunks.sql
\i ./plpgsql/chunk_pgplsql_lib/register_chunk_run.sql
\i ./plpgsql/chunk_pgplsql_lib/show_run_status_helper.sql
\i ./plpgsql/chunk_pgplsql_lib/lock_chunk_run.sql
\i ./plpgsql/chunk_pgplsql_lib/execute_chunk_stmt.sql
\i ./plpgsql/chunk_pgplsql_lib/is_integer.sql
\i ./plpgsql/chunk_pgplsql_lib/get_integer.sql
\i ./plpgsql/chunk_pgplsql_lib/is_varchar.sql
\i ./plpgsql/chunk_pgplsql_lib/get_varchar.sql
\i ./plpgsql/chunk_pgplsql_lib/is_timestamptz.sql
\i ./plpgsql/chunk_pgplsql_lib/get_timestamptz.sql
\i ./plpgsql/chunk_pgplsql_lib/replace_tags_in_key_clause.sql
\i ./plpgsql/chunk_pgplsql_lib/replace_table_tags.sql
\i ./plpgsql/chunk_pgplsql_lib/is_key_equal.sql
\i ./plpgsql/chunk_pgplsql_lib/pk2_execute_final.sql
\i ./plpgsql/chunk_pgplsql_lib/pk2_execute_k1_e_k2_n.sql
\i ./plpgsql/chunk_pgplsql_lib/pk2_execute_k1_n.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_execute_final.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_execute_k1_e_k2_e_k3_n.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_execute_k1_e_k2_n.sql
\i ./plpgsql/chunk_pgplsql_lib/pk3_execute_k1_n.sql
\i ./plpgsql/chunk_pgplsql_lib/assert_lower_chunk_found.sql
\i ./plpgsql/chunk_pgplsql_lib/assert_upper_chunk_found.sql
\i ./plpgsql/chunk_pgplsql_lib/assert_number_chunks_not_zero.sql
\i ./plpgsql/chunk_pgplsql_lib/raise_key_values_exception.sql
\i ./plpgsql/chunk_pgplsql_lib/log_statements.sql
\i ./plpgsql/chunk_pgplsql_lib/get_varchar_representation.sql


\i ./plpgsql/chunk_pgplsql/execute_dml.sql
\i ./plpgsql/chunk_pgplsql/show_queries.sql
\i ./plpgsql/chunk_pgplsql/mark_runs_complete.sql
\i ./plpgsql/chunk_pgplsql/show_run_status.sql
\i ./plpgsql/chunk_pgplsql/show_active_run_status.sql
\i ./plpgsql/chunk_pgplsql/show_all_run_status.sql
\i ./plpgsql/chunk_pgplsql/delete_run.sql

